// <auto-generated />
using System;
using AlmacenSC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlmacenSC.Migrations
{
    [DbContext(typeof(AlmacenSCContext))]
    [Migration("20251123200619_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlmacenSC.Core.Entities.AlertaReabastecimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Atendida")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAlerta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InventarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventarioId");

                    b.ToTable("AlertaReabastecimiento");
                });

            modelBuilder.Entity("AlmacenSC.Core.Entities.CargaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SolicitadoPor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CargaProducto");
                });

            modelBuilder.Entity("AlmacenSC.Core.Entities.CargaProductoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("CargaProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoEntradaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CargaProductoId");

                    b.HasIndex("ProductoEntradaId");

                    b.ToTable("CargaProductoDetalle");
                });

            modelBuilder.Entity("AlmacenSC.Core.Entities.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductoEntradaId")
                        .HasColumnType("integer");

                    b.Property<int>("StockActual")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoEntradaId")
                        .IsUnique();

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("AlmacenSC.Core.Entities.ProductoEntrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockMaximo")
                        .HasColumnType("integer");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ProductoEntrada");
                });

            modelBuilder.Entity("AlmacenSC.Core.Entities.ProductoSalida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductoEntradaId")
                        .HasColumnType("integer");

                    b.Property<string>("SolicitadoPor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductoEntradaId");

                    b.ToTable("ProductoSalida");
                });

            modelBuilder.Entity("AlmacenSC.Core.Entities.AlertaReabastecimiento", b =>
                {
                    b.HasOne("AlmacenSC.Core.Entities.Inventario", "Inventario")
                        .WithMany()
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("AlmacenSC.Core.Entities.CargaProductoDetalle", b =>
                {
                    b.HasOne("AlmacenSC.Core.Entities.CargaProducto", "CargaProducto")
                        .WithMany("Detalles")
                        .HasForeignKey("CargaProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlmacenSC.Core.Entities.ProductoEntrada", "ProductoEntrada")
                        .WithMany()
                        .HasForeignKey("ProductoEntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargaProducto");

                    b.Navigation("ProductoEntrada");
                });

            modelBuilder.Entity("AlmacenSC.Core.Entities.Inventario", b =>
                {
                    b.HasOne("AlmacenSC.Core.Entities.ProductoEntrada", "ProductoEntrada")
                        .WithOne("Inventario")
                        .HasForeignKey("AlmacenSC.Core.Entities.Inventario", "ProductoEntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductoEntrada");
                });

            modelBuilder.Entity("AlmacenSC.Core.Entities.ProductoSalida", b =>
                {
                    b.HasOne("AlmacenSC.Core.Entities.ProductoEntrada", "ProductoEntrada")
                        .WithMany()
                        .HasForeignKey("ProductoEntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductoEntrada");
                });

            modelBuilder.Entity("AlmacenSC.Core.Entities.CargaProducto", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("AlmacenSC.Core.Entities.ProductoEntrada", b =>
                {
                    b.Navigation("Inventario")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
